DEFAULT_CLASSIFICATION_RULES: list[dict] = [
    # Source category mappings from statement CSVs.
    {"rule_type": "source_category_contains", "pattern": "merchandise", "category": "merchandise_shopping", "confidence": 0.93, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "groceries", "category": "groceries_other", "confidence": 0.90, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "dining", "category": "eating_out", "confidence": 0.90, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "restaurant", "category": "eating_out", "confidence": 0.90, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "subscription", "category": "subscriptions", "confidence": 0.94, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "travel", "category": "travel", "confidence": 0.90, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "transportation", "category": "transportation", "confidence": 0.90, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "utility", "category": "utilities", "confidence": 0.92, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "insurance", "category": "insurance", "confidence": 0.92, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "health", "category": "healthcare", "confidence": 0.88, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "education", "category": "education", "confidence": 0.88, "priority": 10},
    {"rule_type": "source_category_contains", "pattern": "entertainment", "category": "entertainment", "confidence": 0.88, "priority": 10},
    # Keyword mappings.
    {"rule_type": "text_contains", "pattern": "patel", "category": "groceries_indian", "confidence": 0.92, "priority": 50},
    {"rule_type": "text_contains", "pattern": "apna bazaar", "category": "groceries_indian", "confidence": 0.92, "priority": 50},
    {"rule_type": "text_contains", "pattern": "indian grocery", "category": "groceries_indian", "confidence": 0.92, "priority": 50},
    {"rule_type": "text_contains", "pattern": "india cash and carry", "category": "groceries_indian", "confidence": 0.92, "priority": 50},
    {"rule_type": "text_contains", "pattern": "whole foods", "category": "groceries_other", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "trader joe", "category": "groceries_other", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "costco", "category": "groceries_other", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "safeway", "category": "groceries_other", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "walmart grocery", "category": "groceries_other", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "restaurant", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "doordash", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "ubereats", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "grubhub", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "cafe", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "starbucks", "category": "eating_out", "confidence": 0.88, "priority": 50},
    {"rule_type": "text_contains", "pattern": "amazon", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "target", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "best buy", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "macy", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "nike", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "etsy", "category": "merchandise_shopping", "confidence": 0.87, "priority": 50},
    {"rule_type": "text_contains", "pattern": "netflix", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "spotify", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "youtube", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "prime", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "icloud", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "openai", "category": "subscriptions", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "airlines", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "hotel", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "marriott", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "hilton", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "airbnb", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "lyft", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "uber trip", "category": "travel", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "shell", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "chevron", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "exxon", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "parking", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "bart", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "metro", "category": "transportation", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "pg&e", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "comcast", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "xfinity", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "at&t", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "verizon", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "water utility", "category": "utilities", "confidence": 0.90, "priority": 50},
    {"rule_type": "text_contains", "pattern": "geico", "category": "insurance", "confidence": 0.91, "priority": 50},
    {"rule_type": "text_contains", "pattern": "state farm", "category": "insurance", "confidence": 0.91, "priority": 50},
    {"rule_type": "text_contains", "pattern": "progressive", "category": "insurance", "confidence": 0.91, "priority": 50},
    {"rule_type": "text_contains", "pattern": "insurance", "category": "insurance", "confidence": 0.91, "priority": 50},
    {"rule_type": "text_contains", "pattern": "pharmacy", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "walgreens", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "cvs", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "kaiser", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "hospital", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "dental", "category": "healthcare", "confidence": 0.85, "priority": 50},
    {"rule_type": "text_contains", "pattern": "movie", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "cinema", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "steam", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "playstation", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "xbox", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "amc", "category": "entertainment", "confidence": 0.83, "priority": 50},
    {"rule_type": "text_contains", "pattern": "coursera", "category": "education", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "udemy", "category": "education", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "university", "category": "education", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "tuition", "category": "education", "confidence": 0.84, "priority": 50},
    {"rule_type": "text_contains", "pattern": "textbook", "category": "education", "confidence": 0.84, "priority": 50},
]
